db.restaurants.find()
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({},{restaurant_id:1,name:1,borough:1,"address.zipcode":1,_id:0})
db.restaurants.find({borough:"Bronx"})
db.restaurants.find({borough:"Bronx"}).limit(5)
db.restaurants.find({borough:"Bronx"}).skip(5).limit(5)
db.restaurants.find({grades:{$elemMatch:{score:{$gt:90}}}})
db.restaurants.find({grades:{$elemMatch:{score:{$gt:80,$lt:100}}}})
db.restaurants.find({"address.coord.0":{$lt:-95.754168}})
db.restaurants.find({$and:[{cuisine:{$not:/American/i}},{grades:{$elemMatch:{score:{$gt:70}}}},{"address.coord.0":{$lt:-65.754168}}]})
db.restaurants.find({cuisine:{$not:/American/i},grades:{$elemMatch:{score:{$gt:70}}},"address.coord.0":{$lt:-65.754168}})
db.restaurants.find({cuisine:{$not:/American/i},grades:{$elemMatch:{grade:"A"}},borough:{$not:/Brooklyn/i}}).sort({cuisine:-1})
db.restaurants.find({name:/^Wil/i},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({name:/ces$/i},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({name:/Reg/i},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({cuisine:{$in:[/American/i,/Chinese/i]},borough:"Bronx"})
db.restaurants.find({borough: { $in: [/Staten Island/i,/Queens/i,/Bronx/i,/Brooklyn/i]}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({borough: { $nin: [/Staten Island/i,/Queens/i,/Bronx/i,/Brooklyn/i]}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({grades:{$not:{$elemMatch:{score:{$gt:10}}}}},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({$or: [{name:/fish/i, cuisine: {$nin:[/American/i,/Chinese/i]}},{name:/^Wil/}]},{restaurant_id:1,name:1,borough:1,cuisine:1,_id:0})
db.restaurants.find({grades:{$elemMatch:{grade:"A",score:11,date:{$eq:new ISODate('2014-08-11T00:00:00Z')}}}},{restaurant_id:1,name:1,grades:1,_id:0})
db.restaurants.find({"grades.1.grade":"A","grades.1.score":9,"grades.1.date":{$eq:new ISODate('2014-08-11T00:00:00Z')}},{restaurant_id:1,name:1,grades:1,_id:0})
db.restaurants.find({"address.coord.1":{$gt:42,$lte:52}},{restaurant_id:1,name:1,"address.street":1,"address.coord":1,_id:0})
db.restaurants.find().sort({name:1})
db.restaurants.find().sort({name:-1})
db.restaurants.find().sort({cuisine:1,borough:-1})
db.restaurants.find({"address.street":{$exists: false}})
db.restaurants.find({"address.coord":{$type:"double"}})
db.restaurants.find({grades:{$elemMatch:{score:{$mod:[7,0]}}}},{restaurant_id:1,name:1,grades:1,_id:0}) 
db.restaurants.find({name:/mon/i},{name:1,borough:1,"address.coord":1,cuisine:1,_id:0})
db.restaurants.find({name:/^Mad/},{name:1,borough:1,"address.coord":1,cuisine:1,_id:0})
